#加密密钥
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: 123456
#    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    bean: JasyptUtils
spring:
  application:
    name: user-center
  # session失效时间(分钟)
  session:
    timeout: 86400
    store-type: redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter?&serverTimezone=Asia/Shanghai
    username: root
#    password: ENC(Hi3K8jwW+GApVZcR1Fo4dw==)
    password: root
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    #password: ENC(lpmF+Hf/vfUhh5PtVoqCpg==)
    password: 123456
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl